# Generated by Django 3.2.13 on 2022-05-14 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='picture',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
    ]
